### ISSUE TITLE
`build` target is too heavyweight

### ISSUE THREAD

**Issue by amake** [jojojames/flycheck-gradle#1]
Hi. Thank you for the useful package.

I tried it out with a project of mine, but I found that the default build target of `build` is far too heavyweight in my case. I use the [Application plugin](https://docs.gradle.org/current/userguide/application_plugin.html), which means `build` includes not only the `compile*` target, but also `assemble` (building *all* distfiles) and `check`, which in my case runs Checkstyle, FindBugs, and unit tests.

For the purposes of Flycheck, I would think that just the appropriate `compile*` target would be better. The downside would be having to split target generation according to language (`compileJava`, `compileKotlin`(?), etc.). If you disagree, perhaps the target could be made customizable.

**Comment by jojojames** [comment]
Sounds good, let me:

1. See if compile* is a suitable default.
2. Look into making the compile target customizable.

For now as a quick workaround, you could probably advise flycheck-gradle--warm-or-cold-build and set the value you want.

**Comment by jojojames** [comment]
Added support for a custom function to designate which compile command you want.

I've set a default for kotlin, I'm not too sure what's appropriate for java so it's still set to 'gradle clean build'. If you had an idea what's appropriate for java, I'd appreciate a pull request.

Thanks for bringing this issue up!
